## PROFILE DEV

server:
  servlet:
    context-path: /pm/api
  port: 3000
spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:mysql://localhost:3306/pm_patients
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ##format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql